# Generated by Django 4.1.5 on 2023-02-02 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_userdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='Interests',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Interests',
            field=models.ManyToManyField(to='base.category'),
        ),
    ]
